export const colors = {
  background: 'var(--background)',
  panel: 'var(--background-panel)',
  elevated: 'var(--background-elevated)',
  input: 'var(--background-input)',
  subtle: 'var(--background-subtle)',
  foreground: 'var(--foreground)',
  textPrimary: 'var(--text-primary)',
  textSecondary: 'var(--text-secondary)',
  textTertiary: 'var(--text-tertiary)',
  textInverse: 'var(--text-inverse)',
  brand: {
    DEFAULT: 'var(--brand)',
    dim: 'var(--brand-dim)',
    border: 'var(--brand-border)',
    hover: 'var(--brand-hover)',
    glow: 'var(--brand-glow)',
  },
  positive: 'var(--positive)',
  positiveBg: 'var(--positive-bg)',
  negative: 'var(--negative)',
  negativeBg: 'var(--negative-bg)',
  warning: 'var(--warning)',
  warningBg: 'var(--warning-bg)',
  success: 'var(--success)',
  destructive: 'var(--destructive)',
  border: 'var(--border)',
  borderStrong: 'var(--border-strong)',
  borderSubtle: 'var(--border-subtle)',
  ring: 'var(--brand)',
} as const;

export type ColorKey = keyof typeof colors;
